export const SET_USER_IMAGES = 'SET_USER_IMAGES';
export const FETCH_USER_IMAGES_FAILED = 'FETCH_USER_IMAGES_FAILED';
export const SET_USER_IMAGES_FROM_CACHE = 'SET_USER_IMAGES_FROM_CACHE';
export const UPDATE_USER_IAMGE = 'UPDATE_USER_IAMGE';
export const CLEAR_UP_CURRENT_USER = 'CLEAR_UP_CURRENT_USER';

export const SET_USERS = 'SET_USERS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

